openapi: 3.0.0
info:
  description: Example API with references
  title: Example API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get users list
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: User created
  /users/{id}:
    get:
      summary: Get user by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        500:
          $ref: '../common/responses.yaml#/components/responses/500'
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          $ref: '../common/responses.yaml#/components/responses/404'
  /pets:
    get:
      summary: Get pets list
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        403:
          $ref: '../common/responses.yaml#/components/responses/403'
        404:
          $ref: '../common/responses.yaml#/components/responses/404'
        500:
          $ref: '../common/responses.yaml#/components/responses/500'
    post:
      summary: Create new pet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        403:
          $ref: '../common/responses.yaml#/components/responses/403'
        404:
          $ref: '../common/responses.yaml#/components/responses/404'
        500:
          $ref: '../common/responses.yaml#/components/responses/500'
        201:
          description: Pet created
components:
  schemas:
    User:
      type: object
      required:
        - username
        - email
      properties:
        email:
          type: string
          format: email
        id:
          type: integer
          format: int64
        username:
          type: string
    Pet:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
