services:
  get:
    summary: Get all usecases
    description: Get all usecases
    operationId: GetServices
    tags:
      - usecases
    responses:
      '200':
        description: List of usecases
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Service'
  post:
    summary: Create a new service
    description: Create a new service
    operationId: CreateService
    tags:
      - usecases
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServiceCreate'
    responses:
      '201':
        description: Service created successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
      '400':
        $ref: '../components/responses.yaml#/components/responses/400'
      '401':
        $ref: '../components/responses.yaml#/components/responses/401'
      '403':
        $ref: '../components/responses.yaml#/components/responses/403'

service-by-id:
  get:
    summary: Get service by id
    description: Get service by id
    operationId: GetServiceById
    tags:
      - usecases
    parameters:
      - title: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    responses:
      '200':
        description: Service details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
      '400':
        $ref: '../components/responses.yaml#/components/responses/400'
      '401':
        $ref: '../components/responses.yaml#/components/responses/401'
  patch:
    summary: Update service
    description: Update service details
    operationId: UpdateService
    tags:
      - usecases
    parameters:
      - title: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServiceUpdate'
    responses:
      '200':
        description: Service updated successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
      '400':
        $ref: '../components/responses.yaml#/components/responses/400'
      '401':
        $ref: '../components/responses.yaml#/components/responses/401'
      '403':
        $ref: '../components/responses.yaml#/components/responses/403'
      '404':
        $ref: '../components/responses.yaml#/components/responses/404'
  delete:
    summary: Delete service
    description: Delete service
    operationId: DeleteService
    tags:
      - usecases
    parameters:
      - title: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    responses:
      '204':
        description: Service deleted successfully
      '400':
        $ref: '../components/responses.yaml#/components/responses/400'
      '401':
        $ref: '../components/responses.yaml#/components/responses/401'
      '403':
        $ref: '../components/responses.yaml#/components/responses/403'
      '404':
        $ref: '../components/responses.yaml#/components/responses/404'
services-search:
  get:
    summary: Search services
    description: Search services
    operationId: SearchServices
    tags:
      - usecases
    parameters:
      - name: search
        in: query
        required: true
        schema:
          type: string
    responses:
      '200':
        description: List of services
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Service'
components:
  schemas:
    Service:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        specialization:
          $ref: './specializations.yaml#/components/schemas/Specialization'
      required:
        - id
        - title
        - specialization
    ServiceCreate:
      type: object
      properties:
        title:
          type: string
        specialization_id:
          type: integer
          format: int64
      required:
        - title
        - specialization_id
    ServiceUpdate:
      type: object
      properties:
        title:
          type: string
        specialization_id:
          type: integer
          format: int64
