trainings:
  get:
    summary: Get all trainings
    description: Get all trainings
    operationId: GetTrainings
    tags:
      - trainings
    responses:
      '200':
        description: List of trainings
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Training'
  post:
    summary: Create a new training
    description: Create a new training
    operationId: CreateTraining
    tags:
      - trainings
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TrainingCreate'
    responses:
      '201':
        description: Training created successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Training'
      '400':
        $ref: '../components/responses.yaml#/components/responses/400'
      '401':
        $ref: '../components/responses.yaml#/components/responses/401'
      '403':
        $ref: '../components/responses.yaml#/components/responses/403'

training-by-id:
  get:
    summary: Get training by id
    description: Get training by id
    operationId: GetTrainingById
    tags:
      - trainings
    parameters:
      - title: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    responses:
      '200':
        description: Training details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Training'
      '400':
        $ref: '../components/responses.yaml#/components/responses/400'
      '404':
        $ref: '../components/responses.yaml#/components/responses/404'
  patch:
    summary: Update training
    description: Update training details
    operationId: UpdateTrainingById
    tags:
      - trainings
    parameters:
      - title: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TrainingUpdate'
    responses:
      '200':
        description: Training updated successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Training'
      '400':
        $ref: '../components/responses.yaml#/components/responses/400'
      '401':
        $ref: '../components/responses.yaml#/components/responses/401'
      '403':
        $ref: '../components/responses.yaml#/components/responses/403'
      '404':
        $ref: '../components/responses.yaml#/components/responses/404'
  delete:
    summary: Delete specialization
    description: Delete specialization
    operationId: DeleteSpecializationById
    tags:
      - specializations
    parameters:
      - title: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    responses:
      '204':
        description: Specialization deleted successfully
      '400':
        $ref: '../components/responses.yaml#/components/responses/400'
      '401':
        $ref: '../components/responses.yaml#/components/responses/401'
      '403':
        $ref: '../components/responses.yaml#/components/responses/403'
      '404':
        $ref: '../components/responses.yaml#/components/responses/404'

components:
  schemas:
    Training:
      type: object
      properties:
        id:
          type: integer
          format: int64
        master:
          $ref: './masters.yaml#/components/schemas/Master'
        city:
          $ref: './geo.yaml#/components/schemas/City'
        title:
          type: string
        description:
          type: string
        startDate:
          type: string
          pattern: '^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-\d{4}$'
          example: '07-05-2025'
        endDate:
          type: string
          pattern: '^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-\d{4}$'
          example: '07-05-2025'
        price:
          type: number
          format: float
        currency:
          $ref: './geo.yaml#/components/schemas/Currency'
        conditions:
          type: string
        trainingType:
          type: string
        groupSize:
          type: integer
          format: int
        currentGroupSize:
          type: integer
          format: int
        isActive:
          type: boolean
          description: Status for owner only
      required:
        - id
        - title
        - master
        - city
        - startDate
        - endDate
        - price
        - currency
        - conditions
        - trainingType
        - groupSize
        - currentGroupSize

    TrainingCreate:
      type: object
      properties:
        masterId:
          type: integer
          format: int64
        cityId:
          type: integer
        title:
          type: string
          maxLength: 150
        description:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        price:
          type: number
          format: float
        currencyId:
          type: integer
        conditions:
          type: string
        trainingType:
          type: string
        groupSize:
          type: integer
          format: int
        isActive:
          type: boolean
      required:
        - title
        - masterId
        - cityId
        - startDate
        - endDate
        - price
        - currencyId
        - trainingType
        - groupSize

    TrainingUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 150
        description:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        price:
          type: number
          format: float
        currencyId:
          type: integer
        conditions:
          type: string
        trainingType:
          type: string
        groupSize:
          type: integer
          format: int
        currentGroupSize:
          type: integer
          format: int
